### ISSUE TITLE
URL to register volunteer/parent

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#119]
Let's say I want to direct volunteers to a registration page and have them skip the role select step.

I would love to have:
- [ ] http://coderdojochi.org/accounts/register/volunteer
- [ ] http://coderdojochi.org/accounts/register/guardian

Thoughts @bkellgren?

**Comment by bkellgren** [comment]
Doable, we would just extend our registration view to predefine those values on registration and include the unique fields (mentor bio and guardian phone)


On March 4, 2015 at 12:42:08 PM, Ali Karbassi (notifications@github.com) wrote:

Let's say I want to direct volunteers to a registration page and have them skip the role select step.

I would love to have:

 http://coderdojochi.org/accounts/register/volunteer
 http://coderdojochi.org/accounts/register/guardian
Thoughts @bkellgren?

**Comment by karbassi** [comment]
:+1:

**Comment by karbassi** [comment]
This issue was moved to CoderDojoChi/c2#80
