### ISSUE TITLE
Volunteer page copy needs to be modified

### ISSUE THREAD

**Issue by davidkam** [CoderDojoChi/coderdojochi#16]
Currently:
> We'd like to invite you to find out what it's like to help shape the minds of tomorrow by giving you the opportunity to volunteer at our next event. If you are passionate about coding and teaching children, join us. Everyone is welcome, regardless of technical ability. To join and attend our next meeting please sign up below.
> 
> If you are unable to attend meetings and setup CoderDojo Chicago, but would still like to help, we are in need of volunteers and sponsors who can simply help spread the word, recruit new mentors, donate equipment, space and more.
> 
> - All teaching sessions run between 10am and 1pm with breaks and food provided.
> - Volunteers are requested to be there between 9am and 2pm on the event day (Saturday) for setup and breakdown.
> - The only thing you need to bring is yourself, willingness to help new programmers learn, and a fun, cheerful attitude!

First paragraph, second sentence - IMHO, I would remove the part "about coding" and leave it as "passionate about teaching children" (or change it to "passionate about STEM and teaching children") as we don't want to make it seem like you need to be technical, even though you explicitly call it out in the next   sentence. 

Second paragraph, first sentence - missing a word.

**Comment by bkellgren** [comment]
@karbassi   Not sure what you were going for with this sentence either, can you update accordingly?

>If you are unable to attend meetings and setup CoderDojo Chicago, but would still like to help, we are in need of volunteers and sponsors who can simply help spread the word, recruit new mentors, donate equipment, space and more.
