### ISSUE TITLE
Classes show up as full when spots are available

### ISSUE THREAD

**Issue by kapil1garg** [CoderDojoChi/coderdojochi#160]
On the "Classes" screen, March 28 and April 11 shows up as full but there are available spots when the class is clicked. 
![screen shot 2015-03-20 at 5 42 43 pm](https://cloud.githubusercontent.com/assets/3069370/6762111/daa35d0a-cf28-11e4-9fc0-239e037f995c.png)
![screen shot 2015-03-20 at 5 42 59 pm](https://cloud.githubusercontent.com/assets/3069370/6762112/daa560e6-cf28-11e4-9bff-d47f5a99a1c8.png)

**Comment by bkellgren** [comment]
fixed by https://github.com/CoderDojoChi/coderdojochi/pull/161
