### ISSUE TITLE
When logged in as mentor only show "full" status when mentor list is full.

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#202]
![screen shot 2015-06-04 at 18 38 59](https://cloud.githubusercontent.com/assets/17738/7996701/fb809154-0ae8-11e5-9bca-19c00376186b.png)

The class in the screenshot is full with students, not mentors.

**Comment by pjsier** [comment]
It looks like this has been partially fixed, from what I can tell it looks like only non-mentors would see "Join Waitlist" if a class is at student capacity. But it'll still show "Volunteer" for mentors if it's at or over capacity. I'll try and add a condition that shows a waitlist option for mentors if it's at mentor capacity as well
