### ISSUE TITLE
Remove email addresses from url and alternate text of volunteer images

### ISSUE THREAD

**Issue by dlarosa** [CoderDojoChi/coderdojochi#238]
It makes email addresses googable and public.

```
<img src="http://coderdojochi.org/media/avatars/test%40gmail.com/resized/175/image.jpg" alt="test@gmail.com" width="175" height="175">
```

**Comment by karbassi** [comment]
This is because of django-avatar. There is a pull request that's open, but not merged.

https://github.com/grantmcconnaughey/django-avatar/pull/105

We might have to find a different avatar package. Any suggestions @bkellgren @dlarosa

**Comment by karbassi** [comment]
Duplicate of #282
