### ISSUE TITLE
Should we list postgresql as prerequisite? 

### ISSUE THREAD

**Issue by dlarosa** [CoderDojoChi/coderdojochi#239]
Should this be a 'requirement' for everyone... ot should we just make them comment out the psycopg2 line on the requirement.txt file?

**Comment by ZahidP** [comment]
@dlarosa I think we should do one or the other, I had to run `brew install postgresql` on my mac before the setup worked.

**Comment by karbassi** [comment]
Fixed since we moved to docker.
