### ISSUE TITLE
Class student data showing all male students

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#265]
Without time to dive deeper, it appears some recent changes to our class stats page broke the totals for attendance and gender.  The actual data is all in tact.

**Comment by karbassi** [comment]
@bkellgren can you add more information? Where does it say that?

**Comment by bkellgren** [comment]
@karbassi my bad, added a further description above

**Comment by pjsier** [comment]
@karbassi any issues with this still or was assigning me just an admin thing?
