### ISSUE TITLE
Need way of indicating reason for people not showing up on check-in page

### ISSUE THREAD

**Issue by pjsier** [CoderDojoChi/coderdojochi#275]
Currently on the check-in page, we can only say whether or not someone showed up. Would be useful to have a button that opened up a text field where we could indicate the reason for them not showing. That way, we can if people have a reason for not showing up, and how many are just no-shows

**Comment by karbassi** [comment]
I like this idea.

**Comment by karbassi** [comment]
@MVanderwood Add a `notes` field.
