### ISSUE TITLE
Docker slow on AWS

### ISSUE THREAD

**Issue by pjsier** [CoderDojoChi/coderdojochi#279]
The app has been running slow, so I looked up a few resources on handling Docker speed, not sure if any of this will help, but wanted to throw them out:

- Speed up: http://www.danstutzman.com/2014/07/speed-up-docker-on-ec2
- Speeding up w/IP and Flask https://blog.jverkamp.com/2015/04/03/performance-problems-with-flask-and-docker/
- Could potentially be the mounting of linked folders in virtual box: http://www.ybrikman.com/writing/2015/05/19/docker-osx-dev/

**Comment by pjsier** [comment]
It's a long shot, but we could potentially bump the memory in the [Dockerrun.aws.json file|https://github.com/CoderDojoChi/coderdojochi/blob/feature/docker-circleci/deploy/Dockerrun.aws.json] to 4096? Not sure if it'd have an impact, but it fixed a problem I had with different Docker container.

**Comment by karbassi** [comment]
- [ ] Bump the memory in the Dockerrun.aws.json file to 4096
- [ ] Speed up: http://www.danstutzman.com/2014/07/speed-up-docker-on-ec2
- [ ] Could potentially be the mounting of linked folders in virtual box: http://www.ybrikman.com/writing/2015/05/19/docker-osx-dev/

**Comment by karbassi** [comment]
@pjsier @bkellgren Bumping the memory to 4GB didn't do anything to the speed issue.
