### ISSUE TITLE
Import script to bring in old classes and students

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#34]
Here is the export of the recent classes.

https://drive.google.com/drive/u/1/#folders/0B0RkamNp7XAbYUwyblByVURVMDA/0B0RkamNp7XAbOXBJWUMyRXFGeUk/0B-wNI2AycE2TYzgzbWNaTXFDSkE

**Comment by bkellgren** [comment]
hmm well have to think about this because currently orders need to be related to guardians

so we would need to create accounts for all these parents, does that seem spammy?

could be a good way to get them in for another class, let them know we created them an account along with the new site announcement etc

thoughts? @karbassi @davidkam @kapil1garg @zafia

**Comment by zafia** [comment]
Would it be possible to send them an email requesting that they create an account if they are interested in more CoderDojo classes and then sending them to a custom registration link from within that email?

That way we don't have parents registered who are not interested in CDC classes at all.

Just a thought....

**Comment by bkellgren** [comment]
Good idea, i like that


On January 11, 2015 at 10:26:06 AM, Safia Abdalla (notifications@github.com) wrote:

Would it be possible to send them an email requesting that they create an account if they are interested in more CoderDojo classes and then sending them to a custom registration link from within that email?

That way we don't have parents registered who are not interested in CDC classes at all.

Just a thought....

**Comment by bkellgren** [comment]
I say for the time being let's just shoot an email to the unique email list of guardians that have previously attended classes.  In the email we should ask them to reply to request that we auto import their/their student(s) account information.  I will just restore accounts as people request them for now.  Here is the list of unique emails....

APRIL.RANDAZZO0404@GMAIL.COM
AbeSilvia.Martin@gmail.com
Amy@AmySieben.com
BeaLove@InspireByLove.org
CHASEBANK2000@GMAIL.COM
Catie.caya@gmail.com
Djursa@liquidindulgence.com
GTHOE@ALLSTATE.COM
Hankmtu@aol.com
Lkstep@yahoo.com
Nicolerangel@sbcglobal.net
RHONDA.ARMISTEAD@GMAIL.COM
VGARAMIREZ@YAHOO.COM
abesilvia.martin@gmail.com
alicemccormack85@yahoo.com
amferguson4@gmail.com
amor.dimaano@obf.ateneo.edu
amylfrank@comcast.net
amywoodson@hotmail.com
andee60657@yahoo.com
andiecelerio@comcast.net
andrew@igmo.org
andrewlapaglia@gmail.com
anitacruz65@yahoo.com
annaleeoakley@hotmail.com
annkauth@mac.com
annrenakim@yahoo.com
anrob@live.com
awritersdream@msn.com
bahena414@yahoo.com
bbryan83@aol.com
beata.ralon@gmail.com
beth.beyer1@gmail.com
biliana.todorov@gmail.com
bkroch27@gmail.com
bkroche27@gmail.com
blopec@sbcglobal.net
blueeyesnov@yahoo.com
bmendoza@sapient.com
boggsmom@gmail.com
bonnemier1@yahoo.com
boombar123@aol.com
boyshowpow@gmail.com
brandonjustice@dezineomni.com
browntown3@att.net
brucelyeager@gmail.com
c-lawson@northwestern.edu
caquilus@gmail.com
carla_d_robinson@hotmail.com
carlagamble@gmail.com
carolinaclifford@hotmail.com
cdave24@gmail.com
cebell93@gmail.com
cece1173@aol.com
cgulczynski@comcast.net
chad.owens@draftfcb.com
christie@sourcehealing.com
cinziab@comcast.net
clairemei03@gmail.com
cloudidays@hotmail.com
cnm4000@yahoo.com
coachpink@live.com
colbychapman0@gmail.com
coracuzco@hotmail.com
cydneymlewis@gmail.com
daafrank@gmail.com
dabochat@sbcglobal.net
dahliaelgazzar@gmail.com
danaem13@gmail.com
darwinstheory@me.com
denise.forsythe@comcast.net
dhoog@darwill.com
dimi85.df@gmail.com
diyuca6791@yahoo.com
dots731@yahoo.com
doug.lavainc@gmail.com
drecorp@yahoo.com
drewrobbins@hotmail.com
drnorfleet@yahoo.com
dzaitoon@yahoo.com
eaimiuwu@thoughtworks.com
edwindanromero@gmail.com
edyh1977@yahoo.com
elina@eglawgroup.com
emccullen@me.com
emilymrasmussen@gmail.com
erin.bosak@gmail.com
erintmorgan17@hotmail.com
eseed@gmail.com
estebanbusc@hotmail.com
fez2020@gmail.com
fixsteve@gmail.com
fljones69@hotmail.com
ftruska@gmail.com
gailbert7@gmail.com
garrity7300@yahoo.com
gikas64@aol.com
giomunoz01@gmail.com
grobers8@yahoo.com
grosskristin@hotmail.com
hbrown@bitbend.com
heathermbruno@yahoo.com
heydave8@att.net
hjohnson23@sbcglobal.net
hongbrunner@hotmail.com
hope.anderson_hq@yahoo.com
iamdvsj@gmail.com
itsjanet2@gmail.com
jacakel@yahoo.com
jant43@hotmail.com
jason.fagman@gmail.com
jdicecco@sapient.com
jelena.hazlehurst@usa.com
jennifer.jankowski@gmail.com
jenniferbaker132@gmail.com
jgonzalez@icestars.org
jgonzalez@icstars.org
john.nelson@citrix.com
johnnapk@aol.com
jp11235@gmail.com
jsomoza@sapient.com
juliacmayer@gmail.com
juliapaar@comcast.net
jziemia@gmail.com
kaplan.eric@gmail.com
karonkhaleel@gmail.com
kasorce@yahoo.com
kateburstein31@yahoo.com
kay.han@outlook.com
keeleysorokti1@gmail.com
kelli.hurley@arcww.com
kfriedenberger@sapient.com
khu.qian@gmail.com
kikilizzyisme@gmail.com
kimdrichardson@sbcglobal.net
kimschar@me.com
kmandell2000@yahoo.com
kmcleod@silverpathcapital.com
kobie.robinson@gmail.com
kpope2@depaul.edu
kristianmaystewart@gmail.com
kristiee@sbcglobal.net
kristiez@gmail.com
kristin@henikoff.com
kvrowe@gmail.com
kylalou@yahoo.com
kymfraher@gmail.com
lalibgal@hotmail.com
lauracomiskey@live.com
leleduga@gmail.com
lemkin1@yahoo.com
lewtech@gmail.com
liljrnys@sbcglobal.net
lisa.ackerman@live.com
lisa@lisahazen.com
lisakopac@gmail.com
liz.brant@att.net
looped5@hotmail.com
lorencep@gmail.com
lou74lou@hotmail.com
lpgs@ameritech.net
lryan1015@hotmail.com
luis.bocaletti@gmail.com
luisbazan89@yahoo.com
lulu30_pr@yahoo.com
lyelton@gmail.com
madziastojko@sbcglobal.net
magentaphysics@gmail.com
maggie.young@medtronic.com
maggiedparents@aol.com
maggiezieba@Hotmail.com
maher.harb@harbfinancial.com
mail@sbraverman.com
malfianrasyidin@gmail.com
mari232000@yahoo.com
maryfmaher@gmail.com
mattgordon@gmail.com
matthew.randazzo34@gmail.com
mchiong@sapient.com
mcortez98@yahoo.com
me@haydee.com
meetabhutani@gmail.com
michelle@michellebaert.com
mizwilliams1@yahoo.com
mlwillman@gmail.com
monate1@yahoo.com
mpitzele@gmail.com
mr.cantor@gmail.com
mveronical@comcast.net
nboggisme@yahoo.com
ncastrejon4483@gmail.com
netsanetmw@gmail.com
nharde2003@aol.com
nicolerangel@sbcglobal.net
nswilliams1217@gmail.com
oconnorchicagoo@gmail.com
ojieggleston@gmail.com
paula.a.teichner@viivhealthcare.com
perla@communicaglobal.com
piperbrown1@yahoo.com
pkivanc@gmail.com
pmoukiama@icstars.org
ppostacchini@comcast.net
prater_jill@hotmail.com
purchasing@stratusdigital.com
purohitsmit@live.com
ravolas@hotmail.com
rclayborne@gmail.com
reganburke@hotmail.com
rhawkinslyke@gmail.com
rhoward2727@sbcglobal.net
robert.johnsen@ge.com
robsbash@yahoo.com
rodcjones@comcast.net
roni@discovercg.com
rose@designerrose.com
sabine@frobnet.com
saltouros@gmail.com
sana12wadood@gmail.com
sbturk@aol.com
scspanish1875@gmail.com
sehoey@yahoo.com
seiboldfmly5@comcast.net
sgorny@sapient.com
shanell_oliver1@yahoo.com
shapmax@gmail.com
sharmilart@gmail.com
sharon@moxiejean.com
sheebadaniel99@gmail.com
shellym5100@yahoo.com
siudyl@yahoo.com
siuhardin@sbcglobal.net
skamra@sapient.com
skippy@interlandi.com
slarimer8@gmail.com
smanji4@gmail.com
stacywoodsonteacher@mail.com
sunshineguccigirl.cf@gmail.com
svetbek@yahoo.com
tamm656@aim.com
tararfedorko@gmail.com
tcsblogcamp10@gmail.com
tewert0126@hotmail.com
theresabui21@yahoo.com
thewaterwaka@gmail.com
timothyverduin@gmail.com
tlwelin@comcast.net
toddmarek@aol.com
tom.vandek@gmail.com
tpatterson2771@gmail.com
vanessahernandezgarcia@gmail.com
veruca_salt123@yahoo.com
vniedelson@yahoo.com
vpb909@gmail.com
vtle92@yahoo.com
walkingprocess@gmail.com
wendy@familiesintheloop.com
wendylcarter@att.net
whamfan@yahoo.com
wopalinska@yahoo.com
xandarackerman@gmail.com
yeseniafrancois@yahoo.com

**Comment by karbassi** [comment]
Hmm, let's think this through.

Could we set up something where they would all get an email with copy explaining that they have been auto-imported into the system and they can 'activate' the account by just signing in. Each other them would get a random, one time, password email to them.

Is that possible?

The thing we're trying to avoid is someone signing up and having data already entered. Then we have doubles and that gets confusing for our system.

**Comment by zafia** [comment]
Python has an SMTP library so we could write a script that sends out the emails and have a Python script execute on link click.

**Comment by karbassi** [comment]
@zafia We're using mandrill. 

We just need to write the flow for what I'm talking about.

**Comment by karbassi** [comment]
This issue was moved to CoderDojoChi/c2#83
