### ISSUE TITLE
My Dojo screen - cancel classes

### ISSUE THREAD

**Issue by iancmason** [CoderDojoChi/coderdojochi#342]
Not sure if this is the place to open this issue, so feel free to delete or redirect me if this is the wrong venue. I noticed when I tried to cancel my sign up for a class, my registration on the class list as a volunteer disappeared but it still shows up under my dojo.

Also, under "My Dojo", if I click on "can't make it", it takes me to a screen that says "yes I'm excited" or "nevermind". I wonder if it might make more sense to have an option for "cancel signup" or the like. Thanks!

**Comment by karbassi** [comment]
This could be a bug. @bkellgren I'm assigning this to you.

**Comment by bkellgren** [comment]
PR https://github.com/CoderDojoChi/coderdojochi/pull/346
