### ISSUE TITLE
All first/last names should be on User model exclusively

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#360]
- [x] remove `first_name` and `list_name` fields from Mentor models
- [x] remove `first_name` and `list_name` fields from Guardian models
- [x] update all cases in code where `first_name`/`last_name` is referenced from `Mentor`/`Guardian` rather than `User` directly
- [x] data migration for existing users to ensure User `first_name`/`last_name` is latest from `Mentor`/`Guardian` models

**Comment by karbassi** [comment]
Fixed in #364 and #365
