### ISSUE TITLE
Class reminder needs to be sent only during the hours of 10am and 3pm

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#37]
Currently the email gets sent at a really late hour.

**Comment by bkellgren** [comment]
The only reason you saw those emails late night is because the service wasn't working properly and when I fixed it last night the backlogged emails went out.  This should be a non-issue.

Emails will be sent within two hours after the class start time, once 7 days prior and once 24 hours prior.

**Comment by karbassi** [comment]
:+1:
