### ISSUE TITLE
Create Sponsors page

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#43]
- [ ] New Sponsor model
- [ ] New `/sponsors` page
- [ ] Included platinum sponsor logos on homepage
- [ ] "Sponsored by" option on classes and meetings
- [ ] Ad placements when no active sponsorships
- [ ] Link to '/sponsors'  in footer and homepage copy

**Comment by bkellgren** [comment]
@karbassi  got this started in PR #183

**Comment by karbassi** [comment]
This issue was moved to CoderDojoChi/c2#82
