### ISSUE TITLE
Using a git type flow

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#44]
Thoughts on using the git flow workflow?

git-flow
---
- http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/
- http://nvie.com/git-model
- https://github.com/nvie/gitflow
- https://danielkummer.github.io/git-flow-cheatsheet/

github flow
---
- https://guides.github.com/introduction/flow/index.html
- http://scottchacon.com/2011/08/31/github-flow.html

gitlab flow
---
- https://about.gitlab.com/2014/09/29/gitlab-flow/

**Comment by bkellgren** [comment]
@karbassi related to all the other process oriented tickets
