### ISSUE TITLE
Create 'cancel' button for sessions and meetings

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#471]
- [ ] Cancel button should set a date of when the session/meeting was canceled.
- [ ] Cancel action will email guardians/mentors who signed up about the cancelation.

**Comment by bkellgren** [comment]
This ticket will also cover removal of `Session` `is_public` flag.

**Comment by karbassi** [comment]
This issue was moved to CoderDojoChi/c2#79
