### ISSUE TITLE
Limit user bio length.

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#49]
Only display 50 characters of user bio on the session page.

I say we limit the user bio to 500 chars total. 

When you enter a large amount of text, like when I copied over my bio from the old site, it overflows the page design.

**Comment by bkellgren** [comment]
What user in the session?  The teacher?  I pushed a change about an hour ago that sets that one to 120 characters which is about the max that looks good on the tablet breakpoint.
