### ISSUE TITLE
Use Soft Deletes on Models instead of Hard Delete

### ISSUE THREAD

**Issue by danmconrad** [CoderDojoChi/coderdojochi#534]
The Student model has already had some modifications made, specificallly `model.is_active` to work as a soft delete. Based on [this article](https://medium.com/@adriennedomingus/soft-deletion-in-django-e4882581c340), there is a more sustainable approach.

- [ ] Create a repeatable pattern for a model to be converted to "soft deletable", do this for Student.
- [ ] Create github issues for each model to be converted.

**Comment by karbassi** [comment]
After thinking about it some more, we'd want this on all models. We can hard delete when requested/needed.

**Comment by karbassi** [comment]
This issue was moved to CoderDojoChi/c2#71
