### ISSUE TITLE
Add Mentor birthday

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#554]
We need a way for mentors to enter their birthday. This is going to be used to check to see if they require a background check (under 18 do not), for us to have demographic data to use when promoting the company/business, and much more.

### Requirements
- [x] Needs to be mandatory.
- [x] Needs to add a default birthday for all `mentors` that are already in our system (db).
- [x] Require anyone who has a default birthday to update it with a real birthday.
- [x] Visually update the frontend to ask for this information. Look at the _guardian_ flow for how we did that already.

Related to #553 and #386

**Comment by davidkam** [comment]
Do we need to do anything with the existing "background_check" field based on the value of the mentor birthday field?  Like if they are under 18 at time of signup/record creation, should we just set background_check to true?

Also, what happens to an under 18 mentor once they turn 18?  Do they then need a background check?  Or are they grandfathered in?

**Comment by karbassi** [comment]
> Do we need to do anything with the existing "background_check" field based on the value of the mentor birthday field? Like if they are under 18 at time of signup/record creation, should we just set background_check to true?

The background issue is #553. But to answer your questions. I think the easiest way to update this code is to set the `background_check` field to `True` if they are under 18.

> Also, what happens to an under 18 mentor once they turn 18? Do they then need a background check? Or are they grandfathered in?

They are grandfathered in for now. [Version 2](https://github.com/CoderDojoChi/c2/) of our website will have a new background check service.

**Comment by davidkam** [comment]
OK, so will this workflow work?

New mentor : check mandatory birthday field against current date.  If under 18, set background_check to true.  If over 18, set to false.

Existing mentor : set birthday field to some arbitrary date and make them change it on next log in.  When field is updated, check current age against current date, if under 18, set background_check to true.  If over 18, set background_check to false.  

Or for the existing mentor, should we use create date when checking the age so that mentors who signed up when they were younger than 18 are grandfathered in?   Or is this an edge case we don't even need to worry about?

**Comment by karbassi** [comment]
> New mentor : check mandatory birthday field against current date. If under 18, set `background_check` to true. If over 18, set to false.

Yup. Copy over `get_age()` that's under the `Student` model. Can use `a_mentor.get_age()` in the view.

> Existing mentor : set birthday field to some arbitrary date and make them change it on next log in. 

Yes

> When field is updated, check current age against current date, if under 18, set background_check to true. If over 18, set background_check to false.

Almost. 

- If the `background_check` is already true, don't touch it. We don't want to flip them to false if they are over 18 and have already done a background check.
- If the `background_check` is already false and the now we know the mentor is under 18, set it to true. 

> Or for the existing mentor, should we use create date when checking the age so that mentors who signed up when they were younger than 18 are grandfathered in? Or is this an edge case we don't even need to worry about?

Don't worry about this.

**Comment by karbassi** [comment]
@davidkam any updates?
