### ISSUE TITLE
Change start of class from 10am to 9am for mentors

### ISSUE THREAD

**Issue by zafia** [CoderDojoChi/coderdojochi#62]
Currently, mentors are told that class will be held from 10am to 1pm. Ideally, we would want them to come at 9am to help setup/chill out with fellow mentors before classes so time needs to be changed.

**Comment by karbassi** [comment]
@bkellgren I know there is "additional instructions" but do you think it would be a good idea to have it show ±1 hour on the event time when the user is logged in as a volunteer?

**Comment by bkellgren** [comment]
Yeah maybe a half hour before and after?

**Comment by karbassi** [comment]
@bkellgren For now, 1 hour before and after. If everyone shows up at 9:30, we wouldn't be ready.

Could we have an option to set the mentor times rather than have a hard-coded ±X hour(s)?

**Comment by bkellgren** [comment]
Yep sounds good


On February 4, 2015 at 11:17:31 AM, Ali Karbassi (notifications@github.com) wrote:

@bkellgren For now, 1 hour before and after. If everyone shows up at 9:30, we wouldn't be ready.

Could we have an option to set the mentor times rather than have a hard-coded ±X hour(s)?

**Comment by bkellgren** [comment]
There are now mentor_start_date and mentor_end_date for session models which defaults to an hour before and after the default start and end times.
