### ISSUE TITLE
Donate on Homepage

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#73]
Let's add the donation widget on the homepage.

Some design ideas

## A
![screen shot 2015-02-09 at 13 44 37](https://cloud.githubusercontent.com/assets/17738/6114472/fc3da378-b063-11e4-8749-d56814220356.png)

## B
![screen shot 2015-02-09 at 13 45 07](https://cloud.githubusercontent.com/assets/17738/6114475/019c35dc-b064-11e4-98a1-5431d8bed2fb.png)

@davidkam, @bkellgren: What do you guys think?

**Comment by bkellgren** [comment]
@karbassi  i did coincidentally add a donate link as part of the mission statement but i think with some design love your suggestion could be cool to have the whole functionality there

![screenshot 2015-02-11 17 35 11](https://cloud.githubusercontent.com/assets/481195/6158860/5731069c-b214-11e4-967b-7b846917888c.png)
