### ISSUE TITLE
"Can't make it" button on MyDojo doesn't do anything

### ISSUE THREAD

**Issue by kapil1garg** [CoderDojoChi/coderdojochi#75]
![screen shot 2015-02-10 at 2 32 57 pm](https://cloud.githubusercontent.com/assets/3069370/6135893/e703a11e-b131-11e4-85aa-7eeaf1e8155e.png)

**Comment by bkellgren** [comment]
this is the same issue i mentioned previously, database migration on production fixed it

**Comment by karbassi** [comment]
:+1: Good catch @kapil1garg and good fix @bkellgren
