### ISSUE TITLE
"RSPV" button doesn't do anything

### ISSUE THREAD

**Issue by kapil1garg** [CoderDojoChi/coderdojochi#76]
![screen shot 2015-02-10 at 2 36 20 pm](https://cloud.githubusercontent.com/assets/3069370/6135935/50c3f5f4-b132-11e4-9a5a-4ab3efb28ef8.png)

**Comment by bkellgren** [comment]
Whoops, never migrated the database on production after adding some helper methods to replace generating sign up urls within the templates, this is now fixed and pushed to production, thanks
