### ISSUE TITLE
Deployment Structure

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#77]
Related to #48, but I want to make sure we produce a task list of how commits are done.

The idea is, each commit is assigned to an issue, and it gets deployed to staging first, then to production. I know it makes the process a little slower, but outside of hotfixes, I think it would help.

Here's my thoughts.

1. Each commit is tied to a ticket. That way we can see what's it related to. If you need to fix something, before you commit, create a ticket for it. You can add detail to the ticket later if need be.
1. Any design changes should be discussed and put on staging first.
1. We use [semver](http://semver.org/) and tag hotfixes, patches, releases.
1. Automatic deployment to staging via #48 
1. Minor tags are pushed to production. See [semver](http://semver.org/).

What do you think @bkellgren, @davidkam, @kapil1garg

**Comment by bkellgren** [comment]
@karbassi sounds fine can you implement the related tickets to your liking and publish process requirements to the readme?
