### ISSUE TITLE
Change wording for "You must attend a mentor meeting..."

### ISSUE THREAD

**Issue by kapil1garg** [CoderDojoChi/coderdojochi#78]
![screen shot 2015-02-10 at 2 38 00 pm](https://cloud.githubusercontent.com/assets/3069370/6135962/96a56e90-b132-11e4-8b1e-028577200a11.png)

Maybe to something like, "You cannot sign up for a class until after attending the meeting," to indicate that RSPVing for it isn't enough. Until I talked to @karbassi about it, I didn't know that he would have to add me via the Django admin.

**Comment by karbassi** [comment]
In the future, we can remove this because we want to implement a background check feature for all mentors.
