### ISSUE TITLE
Implement manual background-check system

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#79]
There will have to be some **major thought** put into this as we're dealing with private information of people.

Our goals are:

- [ ] Make sure all our mentors are not on any sexual offender or criminal lists.
- [ ] Make sure **no private information is stored** in our system.
- [ ] \(?) Anyone that is flagged gets an automatically generated email from our system. Work with lawyer about this.
- [ ] \(?) Anyone that is flagged gets an automatically blacklisted from our system.

**Comment by bkellgren** [comment]
@karbassi  some feedback on the above...

re: background checks, there are api's for this but each one will cost us money

re: private information, what do you consider private information?  i would think if we were to want to pay for a background check api we would have a form that passes the mentors information directly to the background check api and returns us a status.  a.k.a. no information would be stored on our end
