### ISSUE TITLE
Do daily db dump

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#82]
Cron job to backup the db at a certain time, daily.

**Comment by bkellgren** [comment]
this will happen each day at 2:30 am

**Comment by karbassi** [comment]
@bkellgren it's not accessible via the web, right? Only SFTP?

**Comment by bkellgren** [comment]
@ali yea ssh only and i actually just changed it so now i am creating a collection of scripts at ~/scripts including production_dump.sh and staging_dump.sh respectively, the cron job is now running the production_dump.sh script

**Comment by ali** [comment]
@bkellgren I think you meant to tag @karbassi, not me (@ali).

**Comment by karbassi** [comment]
Ha ha! I'll make fun @bkellgren for this.

![6lnitkx - imgur](https://cloud.githubusercontent.com/assets/17738/6281424/e4747d36-b886-11e4-9365-98be9aaf9b2a.gif)
