### ISSUE TITLE
Add remote grunt build to simple deployment script

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#86]

**Comment by bkellgren** [comment]
this goes along with the remote deployment process and tagging/branching strategy

**Comment by karbassi** [comment]
from @bkellgren https://community.webfaction.com/questions/18074/run-node-package-commands-outside-of-nodejs-directory

**Comment by karbassi** [comment]
I've installed node but compass isn't installed since it needs ruby. Going to wait until @bkellgren updates the build script in #90

**Comment by karbassi** [comment]
This is the same as #90
