### ISSUE TITLE
Waitlist still available to enrolled students

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#88]

**Comment by bkellgren** [comment]
deployed to staging

**Comment by karbassi** [comment]
Was this fixed in 4b7ca12bc4828e5025d9deac51d7e6840c33d9e0, aa2dd148f456ffccfee7e8dfbf5df348961e065a, d31d86f985782ca7a22fa1465864ab5ebca8dc49, and 7d9b9c94b0159482ca9067d8396671ad53295965?

@bkellgren please confirm.

**Comment by bkellgren** [comment]
@karbassi yeah along with some additional copy/button tweaks in there

**Comment by karbassi** [comment]
Can we delete the branch?

**Comment by bkellgren** [comment]
@karbassi yeah go for it, all done
