### ISSUE TITLE
Switch to gulp and build during deployment

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#90]
- [x] Remove compass
- [x] [gulp-sass](https://www.npmjs.com/package/gulp-sass).
- [x] [spritesmith](https://www.npmjs.com/package/gulp-spritesmith).
- [x] imagemagick to auto create 1x versions of images. Update #121 after.
- [x] build task to generate css/js, mapping, and compressed version.
- [x] set up staging and deployment servers to work with gulp

**Comment by karbassi** [comment]
Side note: node is installed and in the path.

**Comment by karbassi** [comment]
Finished and launched in #129
